### ISSUE TITLE
Requesting package-data from REST-API seems not to work properly

### ISSUE THREAD

**Issue by HebisJC** [hbz/laser#202]
When trying to request data over the interface version of the REST-API I'm getting a 403 Error - forbidden access. 

The requested package was part of our consortium and I was able to access and even export different type-versions of the package over the package-details site. Using the API-site on the other hand didn't work with the same user in common. 

The utilized user had rights to access the API for reading and writing, therefore I also could bypass a previous 401 error but stuck on the 403 .

**Comment by klodav** [comment]
Current Code is deprecated and will be overhaul next release.

**Comment by HebisJC** [comment]
fixed, thanks
