### ISSUE TITLE
Kopieren eines Lizenz-Templates führt zu Fehlermeldung

### ISSUE THREAD

**Issue by peterboehm** [hbz/laser#3]
Auf laser-qa und laser-dev:
Lizenz-Template angelegt (Lizenz-ID: 73) und auf "Lizenz kopieren für: [Konsortium]" geklickt --> Fehlermeldung (hier: laser-qa)

    Error 500: Internal Server Error
    URI
    /myInstitutions/replaceme/actionLicenses
    Class
    java.lang.NullPointerException
    Message
    Cannot get property 'name' on null object
    Trace
        Line | Method
    ->>  702 | newLicense     in com.k_int.kbplus.MyInstitutionsController
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
    |    148 | actionLicenses in     ''
    |    198 | doFilter . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter       in grails.plugin.cache.web.filter.AbstractFilter
    |    100 | $tt__doFilter  in com.k_int.kbplus.filter.ApiFilter
    |   1142 | runWorker      in java.util.concurrent.ThreadPoolExecutor
    |    617 | run . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
    ^    745 | run            in java.lang.Thread

**Comment by klodav** [comment]
Um den Fehler reproduzieren zu können ..

Waren die beiden Felder **Lizenz kopieren für** und **Verweis auf Abonnement** ausgefüllt?

**Comment by klodav** [comment]
Ursache gefunden, wird gefixt

**Comment by klodav** [comment]
Version 0.1.1 enthält den Bugfix und ist bereits auf laser-qa deployed

**Comment by peterboehm** [comment]
Besten Dank, das Kopieren funktioniert jetzt
